import type { WorkbenchCodeHostState } from "../../src/features/code-host/use-workbench-code-host.js"

export function codeHostState(overrides: Partial<WorkbenchCodeHostState> = {}): WorkbenchCodeHostState {
  return {
    accounts: [],
    accountsLoading: false,
    remotes: [],
    repositoryLoading: false,
    selectedAccount: undefined,
    selectedRemote: undefined,
    selectAccount: () => {},
    selectRemote: () => {},
    accountName: "",
    setAccountName: () => {},
    accessToken: "",
    setAccessToken: () => {},
    accountBusy: false,
    connectAccount: () => {},
    disconnectAccount: () => {},
    disconnectConfirmation: undefined,
    pullRequests: [],
    pullRequestsLoading: false,
    hasMorePullRequests: false,
    loadingMorePullRequests: false,
    loadMorePullRequests: () => {},
    selectedPullRequest: undefined,
    selectPullRequest: () => {},
    detail: undefined,
    detailLoading: false,
    checks: [],
    activity: undefined,
    mutationBusy: false,
    error: undefined,
    refresh: () => {},
    pushBranch: "",
    setPushBranch: () => {},
    preparedPush: undefined,
    cancelPreparedPush: () => {},
    canPreparePush: false,
    preparePush: () => {},
    applyPush: () => {},
    headRemoteName: "",
    setHeadRemoteName: () => {},
    baseRemoteName: "",
    setBaseRemoteName: () => {},
    headBranch: "",
    setHeadBranch: () => {},
    baseBranch: "",
    setBaseBranch: () => {},
    pullRequestTitle: "",
    setPullRequestTitle: () => {},
    pullRequestBody: "",
    setPullRequestBody: () => {},
    pullRequestDraft: false,
    setPullRequestDraft: () => {},
    canEnsurePullRequest: false,
    ensurePullRequest: () => {},
    commentBody: "",
    setCommentBody: () => {},
    createComment: () => {},
    canCreateComment: false,
    branch: undefined,
    ...overrides,
  }
}
