use std::{fs, path::Path};

use schemars::{JsonSchema, schema_for};
use serde_json::json;

use crate::wire::*;

use super::{PROTOCOL_VERSION, ProtocolExportError};

pub fn export_json_schemas(shared_package_dir: &Path) -> Result<(), ProtocolExportError> {
    let schema_dir = shared_package_dir.join("generated/schema");
    fs::create_dir_all(&schema_dir)?;

    write_core_schemas(&schema_dir)?;
    write_agent_runtime_schemas(&schema_dir)?;
    write_protocol_version_schema(&schema_dir)?;

    Ok(())
}

pub(super) fn build_runtime_json_schemas()
-> Result<Vec<(&'static str, serde_json::Value)>, ProtocolExportError> {
    let mut schemas = build_core_runtime_json_schemas()?;
    schemas.extend(agent_runtime_runtime_schemas()?);
    Ok(schemas)
}

struct JsonSchemaPublicType {
    write: fn(&Path) -> Result<(), ProtocolExportError>,
    runtime: fn() -> Result<(&'static str, serde_json::Value), ProtocolExportError>,
}

const CANCELLATION_SCHEMAS: &[JsonSchemaPublicType] = &[JsonSchemaPublicType {
    write: write_schema::<DaemonRunCancelParams>,
    runtime: schema_pair::<DaemonRunCancelParams>,
}];

fn write_schema<T: JsonSchema>(schema_dir: &Path) -> Result<(), ProtocolExportError> {
    let schema_path = schema_dir.join(format!("{}.json", simple_type_name::<T>()));
    let schema_json = serde_json::to_string_pretty(&schema_value::<T>()?)?;
    fs::write(schema_path, format!("{schema_json}\n"))?;
    Ok(())
}

fn write_selected_schemas(
    schemas: &[JsonSchemaPublicType],
    schema_dir: &Path,
) -> Result<(), ProtocolExportError> {
    for schema in schemas {
        (schema.write)(schema_dir)?;
    }
    Ok(())
}

fn selected_runtime_schemas(
    schemas: &[JsonSchemaPublicType],
) -> Result<Vec<(&'static str, serde_json::Value)>, ProtocolExportError> {
    schemas.iter().map(|schema| (schema.runtime)()).collect()
}

fn write_core_schemas(schema_dir: &Path) -> Result<(), ProtocolExportError> {
    write_schema::<AgentStreamTurnId>(schema_dir)?;
    write_schema::<AgentStreamItemId>(schema_dir)?;
    write_schema::<AgentToolCallOutcome>(schema_dir)?;
    write_schema::<RuntimeLanePendingState>(schema_dir)?;
    write_schema::<AgentStreamEvent>(schema_dir)?;
    write_schema::<StreamEmission>(schema_dir)?;
    write_schema::<AgentStreamFrame>(schema_dir)?;
    write_schema::<VoicePermissionState>(schema_dir)?;
    write_schema::<VoicePhase>(schema_dir)?;
    write_schema::<VoiceEvent>(schema_dir)?;
    write_schema::<BudgetScope>(schema_dir)?;
    write_schema::<BudgetMetric>(schema_dir)?;
    write_schema::<BudgetBreach>(schema_dir)?;
    write_schema::<BudgetSnapshot>(schema_dir)?;
    write_schema::<BudgetExceededEvent>(schema_dir)?;
    write_schema::<BudgetEvent>(schema_dir)?;
    write_schema::<ArtifactId>(schema_dir)?;
    write_schema::<ArtifactKind>(schema_dir)?;
    write_schema::<ArtifactMetadata>(schema_dir)?;
    write_schema::<ImageMediaType>(schema_dir)?;
    write_schema::<ImageArtifactProvenance>(schema_dir)?;
    write_schema::<ImageArtifactMetadata>(schema_dir)?;
    write_schema::<ArtifactEvent>(schema_dir)?;
    write_schema::<ArtifactSummary>(schema_dir)?;
    write_schema::<ArtifactContentResult>(schema_dir)?;
    write_schema::<ActivityCursor>(schema_dir)?;
    write_schema::<ActivityPageQuery>(schema_dir)?;
    write_schema::<PublicActivityPageItem>(schema_dir)?;
    write_schema::<PublicActivityPageResult>(schema_dir)?;
    write_schema::<AgentTurnsPageQuery>(schema_dir)?;
    write_schema::<AgentUserRow>(schema_dir)?;
    write_schema::<AgentAssistantRow>(schema_dir)?;
    write_schema::<AgentToolCallRow>(schema_dir)?;
    write_schema::<AgentPendingStateRow>(schema_dir)?;
    write_schema::<AgentTurnRow>(schema_dir)?;
    write_schema::<AgentTurnsPageResult>(schema_dir)?;
    write_schema::<ThreadWorkspaceQuery>(schema_dir)?;
    write_schema::<ThreadWorkspaceUpdateCommand>(schema_dir)?;
    write_schema::<ThreadWorkspaceMutation>(schema_dir)?;
    write_schema::<ThreadWorkspacePin>(schema_dir)?;
    write_schema::<ThreadWorkspaceWorkLogEntry>(schema_dir)?;
    write_schema::<ThreadWorkspaceWorkLogKind>(schema_dir)?;
    write_schema::<ThreadWorkspaceResult>(schema_dir)?;
    write_schema::<DaemonEventCursor>(schema_dir)?;
    write_schema::<PublicApprovalEvent>(schema_dir)?;
    write_schema::<ContextReceipt>(schema_dir)?;
    write_schema::<ContextReceiptEvent>(schema_dir)?;
    write_schema::<PublicContextReceipt>(schema_dir)?;
    write_schema::<PublicContextReceiptEvent>(schema_dir)?;
    write_schema::<ReceiptKind>(schema_dir)?;
    write_schema::<ReceiptProvenance>(schema_dir)?;
    write_schema::<ReceiptState>(schema_dir)?;
    write_schema::<RunFailureKind>(schema_dir)?;
    write_schema::<RunStatusReason>(schema_dir)?;
    write_schema::<RunStatusEvent>(schema_dir)?;
    write_schema::<ScheduledWorkId>(schema_dir)?;
    write_schema::<ScheduledWorkOccurrenceId>(schema_dir)?;
    write_schema::<ScheduledWorkExecutionRequest>(schema_dir)?;
    write_schema::<ScheduledWorkUnpublishedResource>(schema_dir)?;
    write_schema::<ScheduledWorkAttentionPolicy>(schema_dir)?;
    write_schema::<ScheduledWorkDefinition>(schema_dir)?;
    write_schema::<ScheduledWorkOccurrenceState>(schema_dir)?;
    write_schema::<ScheduledWorkPreparationTerminal>(schema_dir)?;
    write_schema::<ScheduledWorkOccurrence>(schema_dir)?;
    write_schema::<CreateScheduledWorkRequest>(schema_dir)?;
    write_schema::<CreateScheduledWorkResult>(schema_dir)?;
    write_schema::<ListScheduledWorkRequest>(schema_dir)?;
    write_schema::<ListScheduledWorkResult>(schema_dir)?;
    write_schema::<CancelScheduledWorkRequest>(schema_dir)?;
    write_schema::<PluginId>(schema_dir)?;
    write_schema::<PluginCapability>(schema_dir)?;
    write_schema::<PluginLifecycleState>(schema_dir)?;
    write_schema::<PluginLifecycleFailure>(schema_dir)?;
    write_schema::<PluginInspection>(schema_dir)?;
    write_schema::<PluginInstallation>(schema_dir)?;
    write_schema::<InspectPluginPackageRequest>(schema_dir)?;
    write_schema::<InstallPluginPackageRequest>(schema_dir)?;
    write_schema::<InstallPluginPackageResult>(schema_dir)?;
    write_schema::<ListPluginInstallationsRequest>(schema_dir)?;
    write_schema::<ListPluginInstallationsResult>(schema_dir)?;
    write_schema::<UninstallPluginRequest>(schema_dir)?;
    write_schema::<RunEvent>(schema_dir)?;
    write_schema::<RunReconciledOnStartupEvent>(schema_dir)?;
    write_schema::<TokenUsageRecordedEvent>(schema_dir)?;
    write_schema::<TokenUsageTotals>(schema_dir)?;
    write_schema::<PublicDaemonEvent>(schema_dir)?;
    write_schema::<PublicDaemonEventEnvelope>(schema_dir)?;
    write_schema::<DaemonEventKind>(schema_dir)?;
    write_schema::<WorkspaceId>(schema_dir)?;
    write_schema::<WorkspacePath>(schema_dir)?;
    write_schema::<WorkspacePathError>(schema_dir)?;
    write_schema::<Workspace>(schema_dir)?;
    write_schema::<DaemonWorkspaceOpenParams>(schema_dir)?;
    write_schema::<DaemonWorkspaceOpenResult>(schema_dir)?;
    write_schema::<DaemonProjectOpenParams>(schema_dir)?;
    write_schema::<DaemonProjectOpenResult>(schema_dir)?;
    write_schema::<DaemonWorkspaceListParams>(schema_dir)?;
    write_schema::<DaemonWorkspaceListResult>(schema_dir)?;
    write_schema::<DaemonWorkspaceGetParams>(schema_dir)?;
    write_schema::<DaemonWorkspaceGetResult>(schema_dir)?;
    write_schema::<WorkspaceFileKind>(schema_dir)?;
    write_schema::<WorkspaceFileEntry>(schema_dir)?;
    write_schema::<WorkspaceFileAttachmentRequest>(schema_dir)?;
    write_schema::<WorkspaceFileAttachment>(schema_dir)?;
    write_schema::<NativeImagePreview>(schema_dir)?;
    write_schema::<WorkspaceFileTreeParams>(schema_dir)?;
    write_schema::<WorkspaceFileTreeResult>(schema_dir)?;
    write_schema::<WorkspaceFileReadParams>(schema_dir)?;
    write_schema::<BoundedFileContent>(schema_dir)?;
    write_schema::<WorkspaceFileReadResult>(schema_dir)?;
    write_schema::<WorkspaceFileWriteParams>(schema_dir)?;
    write_schema::<WorkspaceFileWriteResult>(schema_dir)?;
    write_schema::<WorkspaceFileOpenExternalParams>(schema_dir)?;
    write_schema::<WorkspaceFileOpenExternalResult>(schema_dir)?;
    write_schema::<GitChangeKind>(schema_dir)?;
    write_schema::<GitFileStatus>(schema_dir)?;
    write_schema::<GitWorktreeSummary>(schema_dir)?;
    write_schema::<GitRepositorySnapshot>(schema_dir)?;
    write_schema::<GitRepositorySnapshotParams>(schema_dir)?;
    write_schema::<GitRepositorySnapshotResult>(schema_dir)?;
    write_schema::<GitDiffScope>(schema_dir)?;
    write_schema::<GitDiffParams>(schema_dir)?;
    write_schema::<GitDiffResult>(schema_dir)?;
    write_schema::<GitPathsMutationParams>(schema_dir)?;
    write_schema::<GitCommitParams>(schema_dir)?;
    write_schema::<GitMutationResult>(schema_dir)?;
    write_schema::<GitCheckpointPhase>(schema_dir)?;
    write_schema::<GitCheckpointSummary>(schema_dir)?;
    write_schema::<GitCheckpointListParams>(schema_dir)?;
    write_schema::<GitCheckpointListResult>(schema_dir)?;
    write_schema::<GitCheckpointPrepareRevertParams>(schema_dir)?;
    write_schema::<GitCheckpointPrepareRevertResult>(schema_dir)?;
    write_schema::<GitCheckpointApplyRevertParams>(schema_dir)?;
    write_schema::<CodeHostAccountId>(schema_dir)?;
    write_schema::<CodeHostPullRequestId>(schema_dir)?;
    write_schema::<CodeHostProviderKind>(schema_dir)?;
    write_schema::<CodeHostAccount>(schema_dir)?;
    write_schema::<CodeHostAccountListParams>(schema_dir)?;
    write_schema::<CodeHostAccountListResult>(schema_dir)?;
    write_schema::<CodeHostAccountConnectParams>(schema_dir)?;
    write_schema::<CodeHostAccountConnectResult>(schema_dir)?;
    write_schema::<CodeHostAccountDisconnectParams>(schema_dir)?;
    write_schema::<CodeHostAccountDisconnectResult>(schema_dir)?;
    write_schema::<CodeHostRepositoryRef>(schema_dir)?;
    write_schema::<CodeHostRemote>(schema_dir)?;
    write_schema::<CodeHostRepositoryContextParams>(schema_dir)?;
    write_schema::<CodeHostRepositoryContextResult>(schema_dir)?;
    write_schema::<CodeHostCommitSummary>(schema_dir)?;
    write_schema::<CodeHostPushPrepareParams>(schema_dir)?;
    write_schema::<CodeHostPushPrepareResult>(schema_dir)?;
    write_schema::<CodeHostPushApplyParams>(schema_dir)?;
    write_schema::<CodeHostPushApplyResult>(schema_dir)?;
    write_schema::<CodeHostPullRequestState>(schema_dir)?;
    write_schema::<CodeHostPullRequestSummary>(schema_dir)?;
    write_schema::<CodeHostPullRequestDetail>(schema_dir)?;
    write_schema::<CodeHostPage>(schema_dir)?;
    write_schema::<CodeHostPullRequestListParams>(schema_dir)?;
    write_schema::<CodeHostPullRequestDetailParams>(schema_dir)?;
    write_schema::<CodeHostPullRequestEnsureParams>(schema_dir)?;
    write_schema::<CodeHostPullRequestEnsureResult>(schema_dir)?;
    write_schema::<CodeHostCheckStatus>(schema_dir)?;
    write_schema::<CodeHostCheck>(schema_dir)?;
    write_schema::<CodeHostPullRequestChecksResult>(schema_dir)?;
    write_schema::<CodeHostPullRequestChecksParams>(schema_dir)?;
    write_schema::<CodeHostCommentKind>(schema_dir)?;
    write_schema::<CodeHostComment>(schema_dir)?;
    write_schema::<CodeHostReview>(schema_dir)?;
    write_schema::<CodeHostTimelineItem>(schema_dir)?;
    write_schema::<CodeHostPullRequestActivityResult>(schema_dir)?;
    write_schema::<CodeHostPullRequestActivityParams>(schema_dir)?;
    write_schema::<CodeHostPullRequestCommentCreateParams>(schema_dir)?;
    write_schema::<CodeHostPullRequestCommentCreateResult>(schema_dir)?;
    write_schema::<TerminalSessionId>(schema_dir)?;
    write_schema::<TerminalSessionStatus>(schema_dir)?;
    write_schema::<TerminalSessionSummary>(schema_dir)?;
    write_schema::<TerminalSpawnParams>(schema_dir)?;
    write_schema::<TerminalSpawnResult>(schema_dir)?;
    write_schema::<TerminalListParams>(schema_dir)?;
    write_schema::<TerminalListResult>(schema_dir)?;
    write_schema::<TerminalAttachParams>(schema_dir)?;
    write_schema::<TerminalAttachResult>(schema_dir)?;
    write_schema::<TerminalInputParams>(schema_dir)?;
    write_schema::<TerminalInputResult>(schema_dir)?;
    write_schema::<TerminalResizeParams>(schema_dir)?;
    write_schema::<TerminalResizeResult>(schema_dir)?;
    write_schema::<TerminalDetachParams>(schema_dir)?;
    write_schema::<TerminalDetachResult>(schema_dir)?;
    write_schema::<TerminalCloseParams>(schema_dir)?;
    write_schema::<TerminalCloseResult>(schema_dir)?;
    write_schema::<TerminalStreamEvent>(schema_dir)?;
    write_schema::<TerminalEventParams>(schema_dir)?;
    write_schema::<TrustState>(schema_dir)?;
    write_schema::<ExecutionContext>(schema_dir)?;
    write_schema::<WorkspaceScope>(schema_dir)?;
    write_schema::<SandboxProfile>(schema_dir)?;
    write_schema::<ProcessExecPolicy>(schema_dir)?;
    write_schema::<PermissionPolicy>(schema_dir)?;
    write_schema::<NetworkPolicy>(schema_dir)?;
    write_schema::<EnvPolicy>(schema_dir)?;
    write_schema::<WorkspaceCapabilityUnsupported>(schema_dir)?;
    write_schema::<SessionOverviewQuery>(schema_dir)?;
    write_schema::<SessionOverviewResult>(schema_dir)?;
    write_schema::<SessionOverviewLaneStatus>(schema_dir)?;
    write_schema::<ApprovalAttentionState>(schema_dir)?;
    write_schema::<SpaceId>(schema_dir)?;
    write_schema::<ProjectId>(schema_dir)?;
    write_schema::<NavigationSpace>(schema_dir)?;
    write_schema::<NavigationProject>(schema_dir)?;
    write_schema::<ConversationPlacement>(schema_dir)?;
    write_schema::<NavigationConversation>(schema_dir)?;
    write_schema::<NavigationAgentRow>(schema_dir)?;
    write_schema::<NavigationSnapshot>(schema_dir)?;
    write_schema::<DaemonNavigationSnapshotParams>(schema_dir)?;
    write_schema::<DaemonNavigationSnapshotResult>(schema_dir)?;
    write_schema::<DaemonNavigationIntent>(schema_dir)?;
    write_schema::<DaemonNavigationIntentParams>(schema_dir)?;
    write_schema::<DaemonNavigationIntentResult>(schema_dir)?;
    write_schema::<DaemonNavigationSubscribeParams>(schema_dir)?;
    write_schema::<DaemonNavigationSubscribeResult>(schema_dir)?;
    write_schema::<DaemonNavigationInvalidatedParams>(schema_dir)?;
    write_schema::<DaemonActualRuntimeMode>(schema_dir)?;
    write_schema::<DesktopDaemonLifecycleStatus>(schema_dir)?;
    write_schema::<DesktopDaemonLifecycleProjection>(schema_dir)?;
    write_schema::<DaemonClientCapabilities>(schema_dir)?;
    write_schema::<DaemonControlAction>(schema_dir)?;
    write_schema::<DaemonControlErrorCode>(schema_dir)?;
    write_schema::<DaemonServerCapabilities>(schema_dir)?;
    write_schema::<DaemonInitializeParams>(schema_dir)?;
    write_schema::<DaemonInitializeResult>(schema_dir)?;
    write_schema::<DaemonPendingTransitionKind>(schema_dir)?;
    write_schema::<DaemonPendingTransitionView>(schema_dir)?;
    write_schema::<DaemonRuntimeMode>(schema_dir)?;
    write_schema::<WorkspaceSelector>(schema_dir)?;
    write_schema::<DaemonSessionOpenParams>(schema_dir)?;
    write_schema::<DaemonSessionOpenResult>(schema_dir)?;
    write_schema::<DaemonSessionAttachParams>(schema_dir)?;
    write_schema::<DaemonSessionAttachResult>(schema_dir)?;
    write_schema::<DaemonStatusParams>(schema_dir)?;
    write_schema::<DaemonStatusResult>(schema_dir)?;
    write_schema::<DaemonDiagnosticsParams>(schema_dir)?;
    write_schema::<DaemonDiagnostics>(schema_dir)?;
    write_schema::<DaemonDiagnosticError>(schema_dir)?;
    write_schema::<DaemonDiagnosticTokenUsage>(schema_dir)?;
    write_schema::<DaemonSandboxCapabilitySnapshot>(schema_dir)?;
    write_schema::<DaemonProviderHealthDiagnostic>(schema_dir)?;
    write_schema::<DaemonControlStatusResult>(schema_dir)?;
    write_schema::<DaemonSubscribeParams>(schema_dir)?;
    write_schema::<DaemonSubscribeResult>(schema_dir)?;
    write_schema::<DaemonTransitionStatus>(schema_dir)?;
    write_schema::<DelegateRequest>(schema_dir)?;
    write_schema::<ListSessionsQuery>(schema_dir)?;
    write_schema::<GetSessionQuery>(schema_dir)?;
    write_schema::<ListApprovalsQuery>(schema_dir)?;
    write_schema::<ApprovalSnapshotResult>(schema_dir)?;
    write_schema::<crate::wire::WorkItemKey>(schema_dir)?;
    write_schema::<crate::wire::WorkItem>(schema_dir)?;
    write_schema::<WorkItemListResult>(schema_dir)?;
    write_schema::<WorkItemRefreshParams>(schema_dir)?;
    write_schema::<WorkItemDismissParams>(schema_dir)?;
    write_schema::<WorkItemDismissResult>(schema_dir)?;
    write_schema::<WorkItemTriggerParams>(schema_dir)?;
    write_schema::<WorkItemTriggerResult>(schema_dir)?;
    write_schema::<GetArtifactQuery>(schema_dir)?;
    write_schema::<GetRunQuery>(schema_dir)?;
    write_schema::<ListRunsQuery>(schema_dir)?;
    write_schema::<RunListFilter>(schema_dir)?;
    write_schema::<ListNativeRunsRequest>(schema_dir)?;
    write_schema::<RunListEntry>(schema_dir)?;
    write_schema::<ListNativeRunsResult>(schema_dir)?;
    write_schema::<RunLineageGraphRequest>(schema_dir)?;
    write_schema::<RunLineageGraphEdge>(schema_dir)?;
    write_schema::<RunLineageGraphResult>(schema_dir)?;
    write_schema::<GetRunTimelineQuery>(schema_dir)?;
    write_schema::<RunTimeline>(schema_dir)?;
    write_schema::<RunTimelineRun>(schema_dir)?;
    write_schema::<RunTimelineEventKind>(schema_dir)?;
    write_schema::<RunTimelineEvent>(schema_dir)?;
    write_schema::<RunTimelineEventPayload>(schema_dir)?;
    write_schema::<ListArtifactsQuery>(schema_dir)?;
    write_schema::<ArtifactSnapshotResult>(schema_dir)?;
    write_schema::<ListReceiptsRequest>(schema_dir)?;
    write_schema::<ListReceiptsResult>(schema_dir)?;
    write_schema::<PromoteReceiptRequest>(schema_dir)?;
    write_schema::<QuarantineReceiptRequest>(schema_dir)?;
    write_schema::<OutputContractKind>(schema_dir)?;
    write_schema::<CapsuleResult>(schema_dir)?;
    write_schema::<DebugResult>(schema_dir)?;
    write_schema::<PatchResult>(schema_dir)?;
    write_schema::<ReviewResult>(schema_dir)?;
    write_schema::<ReviewVerdict>(schema_dir)?;
    write_schema::<ReviewFinding>(schema_dir)?;
    write_schema::<FindingSeverity>(schema_dir)?;
    write_schema::<TestResult>(schema_dir)?;
    write_schema::<PlanResult>(schema_dir)?;
    write_schema::<PlanStep>(schema_dir)?;
    write_schema::<ValidationError>(schema_dir)?;
    write_schema::<CapsuleRecipe>(schema_dir)?;
    write_schema::<ListRecipesParams>(schema_dir)?;
    write_schema::<RecipeListResponse>(schema_dir)?;
    write_schema::<RecipeValidationError>(schema_dir)?;
    write_schema::<RecipeResolutionError>(schema_dir)?;
    write_schema::<SessionOverview>(schema_dir)?;
    write_schema::<SessionSummary>(schema_dir)?;
    write_schema::<RunHarnessKind>(schema_dir)?;
    write_schema::<RunDetail>(schema_dir)?;
    write_schema::<RunRecord>(schema_dir)?;
    write_schema::<RunSummary>(schema_dir)?;
    write_schema::<ResumeRunRequest>(schema_dir)?;
    write_schema::<ResumeRunResult>(schema_dir)?;
    write_schema::<ResumeRunState>(schema_dir)?;
    write_schema::<ForkRunRequest>(schema_dir)?;
    write_schema::<ForkRunResult>(schema_dir)?;
    write_schema::<ContinueRunRequest>(schema_dir)?;
    write_schema::<ContinueRunResult>(schema_dir)?;
    write_schema::<SwitchAccountAndResumeRequest>(schema_dir)?;
    write_schema::<SwitchAccountAndResumeResult>(schema_dir)?;
    write_schema::<SpawnRunRequest>(schema_dir)?;
    write_schema::<SpawnRunResult>(schema_dir)?;
    write_schema::<JoinRunRequest>(schema_dir)?;
    write_schema::<JoinRunResult>(schema_dir)?;
    write_schema::<SubscribeRunEventsRequest>(schema_dir)?;
    write_schema::<RunEventDelta>(schema_dir)?;
    write_schema::<RunEventStreamError>(schema_dir)?;
    write_schema::<RunEventStreamPayload>(schema_dir)?;
    write_schema::<RunEventStreamItem>(schema_dir)?;
    write_schema::<SubscribeRunEventsResult>(schema_dir)?;
    write_schema::<SessionId>(schema_dir)?;
    write_schema::<SessionAuthority>(schema_dir)?;
    write_schema::<RunId>(schema_dir)?;
    write_schema::<ApprovalId>(schema_dir)?;
    write_schema::<ApprovalScope>(schema_dir)?;
    write_schema::<ApprovalDecision>(schema_dir)?;
    write_schema::<ApprovalResolutionReason>(schema_dir)?;
    write_schema::<ApprovalTarget>(schema_dir)?;
    write_schema::<ApprovalRequest>(schema_dir)?;
    write_schema::<PublicApprovalResolution>(schema_dir)?;
    write_schema::<DaemonApprovalDecideParams>(schema_dir)?;
    write_schema::<DaemonApprovalDecideResult>(schema_dir)?;
    write_schema::<SessionStatus>(schema_dir)?;
    write_schema::<RunStatus>(schema_dir)?;
    write_schema::<StartRunCommand>(schema_dir)?;
    write_schema::<DaemonRunCompleteWithResultParams>(schema_dir)?;
    write_selected_schemas(CANCELLATION_SCHEMAS, schema_dir)?;
    write_schema::<WorkflowDefinition>(schema_dir)?;
    write_schema::<WorkflowSourceBinding>(schema_dir)?;
    write_schema::<WorkflowSourceKind>(schema_dir)?;
    write_schema::<WorkflowOrchestratorPolicy>(schema_dir)?;
    write_schema::<WorkflowRetryPolicy>(schema_dir)?;
    write_schema::<WorkflowPolicy>(schema_dir)?;
    write_schema::<WorkflowApprovalPolicy>(schema_dir)?;
    write_schema::<WorkflowFileWriteApproval>(schema_dir)?;
    write_schema::<WorkflowProcessApproval>(schema_dir)?;
    write_schema::<WorkflowNetworkApproval>(schema_dir)?;
    write_schema::<WorkflowRuntimeProfileRef>(schema_dir)?;
    write_schema::<WorkflowOutputsPolicy>(schema_dir)?;
    write_schema::<WorkflowOutputRequirement>(schema_dir)?;
    write_schema::<WorkflowBudgets>(schema_dir)?;
    write_schema::<WorkflowBudgetLimits>(schema_dir)?;
    write_schema::<WorkflowLoadParams>(schema_dir)?;
    write_schema::<WorkflowReloadParams>(schema_dir)?;
    write_schema::<WorkflowValidateParams>(schema_dir)?;
    write_schema::<WorkflowValidationReport>(schema_dir)?;
    write_schema::<WorkflowValidationError>(schema_dir)?;
    write_schema::<WorkflowStatusResult>(schema_dir)?;
    write_schema::<WorkflowLoadedStatus>(schema_dir)?;
    write_schema::<WorkflowReloadOutcome>(schema_dir)?;
    Ok(())
}

fn write_agent_runtime_schemas(schema_dir: &Path) -> Result<(), ProtocolExportError> {
    write_schema::<AgentRuntimeStrategyId>(schema_dir)?;
    write_schema::<AgentRuntimeModelId>(schema_dir)?;
    write_schema::<AgentRuntimeModelRef>(schema_dir)?;
    write_schema::<AgentRuntimeMediaCapability>(schema_dir)?;
    write_schema::<AgentRuntimeMediaCapabilities>(schema_dir)?;
    write_schema::<AgentRuntimeStrategyHealthStatus>(schema_dir)?;
    write_schema::<AgentRuntimeStrategyHealth>(schema_dir)?;
    write_schema::<AgentRuntimeStrategyInfo>(schema_dir)?;
    write_schema::<AuthMethodId>(schema_dir)?;
    write_schema::<AuthMethodRef>(schema_dir)?;
    write_schema::<AuthProfileId>(schema_dir)?;
    write_schema::<AuthProfileConnectionState>(schema_dir)?;
    write_schema::<AuthProfileLoginMethod>(schema_dir)?;
    write_schema::<AuthProfileRef>(schema_dir)?;
    write_schema::<AuthProfilePreferences>(schema_dir)?;
    write_schema::<AuthProfileUsage>(schema_dir)?;
    write_schema::<AuthProfileUsageWindow>(schema_dir)?;
    write_schema::<AuthProfileState>(schema_dir)?;
    write_schema::<AuthProfileLoginChallenge>(schema_dir)?;
    write_schema::<AuthProfileLoginResult>(schema_dir)?;
    write_schema::<AuthProfileLogoutResult>(schema_dir)?;
    write_schema::<RuntimeExtensionId>(schema_dir)?;
    write_schema::<RuntimeExtensionDescriptor>(schema_dir)?;
    write_schema::<RuntimeExtensionAvailability>(schema_dir)?;
    write_schema::<RuntimeExtensionMcpServer>(schema_dir)?;
    write_schema::<RuntimeExtensionMcpStdioServer>(schema_dir)?;
    write_schema::<RuntimeExtensionMcpHttpServer>(schema_dir)?;
    write_schema::<RuntimeExtensionEnvVar>(schema_dir)?;
    write_schema::<RuntimeExtensionHttpHeader>(schema_dir)?;
    write_schema::<RuntimeExtensionState>(schema_dir)?;
    write_schema::<RuntimeProfileId>(schema_dir)?;
    write_schema::<RuntimePolicyMode>(schema_dir)?;
    write_schema::<RuntimeProfileExecutionKind>(schema_dir)?;
    write_schema::<RuntimeProfileSummary>(schema_dir)?;
    write_schema::<RuntimeProfilePatch>(schema_dir)?;
    write_schema::<AgentRuntimeSelection>(schema_dir)?;
    write_schema::<AgentRuntimeSnapshot>(schema_dir)?;
    write_schema::<GetAgentRuntimeQuery>(schema_dir)?;
    write_schema::<DaemonAgentRuntimePatchProfileParams>(schema_dir)?;
    write_schema::<DaemonAgentRuntimeAuthLoginParams>(schema_dir)?;
    write_schema::<DaemonAgentRuntimeAuthLoginCompleteParams>(schema_dir)?;
    write_schema::<DaemonAgentRuntimeAuthLogoutParams>(schema_dir)?;
    write_schema::<DaemonAgentRuntimeSetExtensionEnabledParams>(schema_dir)?;
    Ok(())
}

fn build_core_runtime_json_schemas()
-> Result<Vec<(&'static str, serde_json::Value)>, ProtocolExportError> {
    let mut schemas = vec![
        schema_pair::<AgentStreamTurnId>()?,
        schema_pair::<AgentStreamItemId>()?,
        schema_pair::<AgentToolCallOutcome>()?,
        schema_pair::<RuntimeLanePendingState>()?,
        schema_pair::<AgentStreamEvent>()?,
        schema_pair::<AgentStreamFrame>()?,
        schema_pair::<BudgetScope>()?,
        schema_pair::<BudgetMetric>()?,
        schema_pair::<BudgetBreach>()?,
        schema_pair::<BudgetSnapshot>()?,
        schema_pair::<BudgetExceededEvent>()?,
        schema_pair::<BudgetEvent>()?,
        schema_pair::<ApprovalDecision>()?,
        schema_pair::<ApprovalResolutionReason>()?,
        schema_pair::<ApprovalId>()?,
        schema_pair::<ApprovalRequest>()?,
        schema_pair::<ApprovalTarget>()?,
        schema_pair::<PublicApprovalEvent>()?,
        schema_pair::<PublicApprovalResolution>()?,
        schema_pair::<ApprovalScope>()?,
        schema_pair::<ActivityCursor>()?,
        schema_pair::<ActivityPageQuery>()?,
        schema_pair::<PublicActivityPageItem>()?,
        schema_pair::<PublicActivityPageResult>()?,
        schema_pair::<AgentTurnsPageQuery>()?,
        schema_pair::<AgentUserRow>()?,
        schema_pair::<AgentAssistantRow>()?,
        schema_pair::<AgentToolCallRow>()?,
        schema_pair::<AgentPendingStateRow>()?,
        schema_pair::<AgentTurnRow>()?,
        schema_pair::<AgentTurnsPageResult>()?,
        schema_pair::<ArtifactId>()?,
        schema_pair::<ArtifactKind>()?,
        schema_pair::<ArtifactMetadata>()?,
        schema_pair::<ImageMediaType>()?,
        schema_pair::<ImageArtifactProvenance>()?,
        schema_pair::<ImageArtifactMetadata>()?,
        schema_pair::<ArtifactEvent>()?,
        schema_pair::<ArtifactSummary>()?,
        schema_pair::<ArtifactContentResult>()?,
        schema_pair::<DaemonClientCapabilities>()?,
        schema_pair::<DaemonEventCursor>()?,
        schema_pair::<ContextReceipt>()?,
        schema_pair::<ContextReceiptEvent>()?,
        schema_pair::<PublicContextReceipt>()?,
        schema_pair::<PublicContextReceiptEvent>()?,
        schema_pair::<ReceiptKind>()?,
        schema_pair::<ReceiptProvenance>()?,
        schema_pair::<ReceiptState>()?,
        schema_pair::<RunFailureKind>()?,
        schema_pair::<RunStatusReason>()?,
        schema_pair::<RunStatusEvent>()?,
        schema_pair::<ScheduledWorkId>()?,
        schema_pair::<ScheduledWorkOccurrenceId>()?,
        schema_pair::<ScheduledWorkExecutionRequest>()?,
        schema_pair::<ScheduledWorkUnpublishedResource>()?,
        schema_pair::<ScheduledWorkAttentionPolicy>()?,
        schema_pair::<ScheduledWorkDefinition>()?,
        schema_pair::<ScheduledWorkOccurrenceState>()?,
        schema_pair::<ScheduledWorkPreparationTerminal>()?,
        schema_pair::<ScheduledWorkOccurrence>()?,
        schema_pair::<CreateScheduledWorkRequest>()?,
        schema_pair::<CreateScheduledWorkResult>()?,
        schema_pair::<ListScheduledWorkRequest>()?,
        schema_pair::<ListScheduledWorkResult>()?,
        schema_pair::<CancelScheduledWorkRequest>()?,
        schema_pair::<RunEvent>()?,
        schema_pair::<RunReconciledOnStartupEvent>()?,
        schema_pair::<TokenUsageRecordedEvent>()?,
        schema_pair::<TokenUsageTotals>()?,
        schema_pair::<PublicDaemonEvent>()?,
        schema_pair::<PublicDaemonEventEnvelope>()?,
        schema_pair::<DaemonEventKind>()?,
        schema_pair::<WorkspaceId>()?,
        schema_pair::<WorkspacePath>()?,
        schema_pair::<WorkspacePathError>()?,
        schema_pair::<Workspace>()?,
        schema_pair::<DaemonWorkspaceOpenParams>()?,
        schema_pair::<DaemonWorkspaceOpenResult>()?,
        schema_pair::<DaemonProjectOpenParams>()?,
        schema_pair::<DaemonProjectOpenResult>()?,
        schema_pair::<DaemonWorkspaceListParams>()?,
        schema_pair::<DaemonWorkspaceListResult>()?,
        schema_pair::<DaemonWorkspaceGetParams>()?,
        schema_pair::<DaemonWorkspaceGetResult>()?,
        schema_pair::<WorkspaceFileKind>()?,
        schema_pair::<WorkspaceFileEntry>()?,
        schema_pair::<WorkspaceFileAttachmentRequest>()?,
        schema_pair::<WorkspaceFileAttachment>()?,
        schema_pair::<NativeImagePreview>()?,
        schema_pair::<WorkspaceFileTreeParams>()?,
        schema_pair::<WorkspaceFileTreeResult>()?,
        schema_pair::<WorkspaceFileReadParams>()?,
        schema_pair::<BoundedFileContent>()?,
        schema_pair::<WorkspaceFileReadResult>()?,
        schema_pair::<WorkspaceFileWriteParams>()?,
        schema_pair::<WorkspaceFileWriteResult>()?,
        schema_pair::<WorkspaceFileOpenExternalParams>()?,
        schema_pair::<WorkspaceFileOpenExternalResult>()?,
        schema_pair::<GitChangeKind>()?,
        schema_pair::<GitFileStatus>()?,
        schema_pair::<GitWorktreeSummary>()?,
        schema_pair::<GitRepositorySnapshot>()?,
        schema_pair::<GitRepositorySnapshotParams>()?,
        schema_pair::<GitRepositorySnapshotResult>()?,
        schema_pair::<GitDiffScope>()?,
        schema_pair::<GitDiffParams>()?,
        schema_pair::<GitDiffResult>()?,
        schema_pair::<GitPathsMutationParams>()?,
        schema_pair::<GitCommitParams>()?,
        schema_pair::<GitMutationResult>()?,
        schema_pair::<GitCheckpointPhase>()?,
        schema_pair::<GitCheckpointSummary>()?,
        schema_pair::<GitCheckpointListParams>()?,
        schema_pair::<GitCheckpointListResult>()?,
        schema_pair::<GitCheckpointPrepareRevertParams>()?,
        schema_pair::<GitCheckpointPrepareRevertResult>()?,
        schema_pair::<GitCheckpointApplyRevertParams>()?,
        schema_pair::<CodeHostAccountId>()?,
        schema_pair::<CodeHostPullRequestId>()?,
        schema_pair::<CodeHostProviderKind>()?,
        schema_pair::<CodeHostAccount>()?,
        schema_pair::<CodeHostAccountListParams>()?,
        schema_pair::<CodeHostAccountListResult>()?,
        schema_pair::<CodeHostAccountConnectParams>()?,
        schema_pair::<CodeHostAccountConnectResult>()?,
        schema_pair::<CodeHostAccountDisconnectParams>()?,
        schema_pair::<CodeHostAccountDisconnectResult>()?,
        schema_pair::<CodeHostRepositoryRef>()?,
        schema_pair::<CodeHostRemote>()?,
        schema_pair::<CodeHostRepositoryContextParams>()?,
        schema_pair::<CodeHostRepositoryContextResult>()?,
        schema_pair::<CodeHostCommitSummary>()?,
        schema_pair::<CodeHostPushPrepareParams>()?,
        schema_pair::<CodeHostPushPrepareResult>()?,
        schema_pair::<CodeHostPushApplyParams>()?,
        schema_pair::<CodeHostPushApplyResult>()?,
        schema_pair::<CodeHostPullRequestState>()?,
        schema_pair::<CodeHostPullRequestSummary>()?,
        schema_pair::<CodeHostPullRequestDetail>()?,
        schema_pair::<CodeHostPage>()?,
        schema_pair::<CodeHostPullRequestListParams>()?,
        schema_pair::<CodeHostPullRequestDetailParams>()?,
        schema_pair::<CodeHostPullRequestEnsureParams>()?,
        schema_pair::<CodeHostPullRequestEnsureResult>()?,
        schema_pair::<CodeHostCheckStatus>()?,
        schema_pair::<CodeHostCheck>()?,
        schema_pair::<CodeHostPullRequestChecksResult>()?,
        schema_pair::<CodeHostPullRequestChecksParams>()?,
        schema_pair::<CodeHostCommentKind>()?,
        schema_pair::<CodeHostComment>()?,
        schema_pair::<CodeHostReview>()?,
        schema_pair::<CodeHostTimelineItem>()?,
        schema_pair::<CodeHostPullRequestActivityResult>()?,
        schema_pair::<CodeHostPullRequestActivityParams>()?,
        schema_pair::<CodeHostPullRequestCommentCreateParams>()?,
        schema_pair::<CodeHostPullRequestCommentCreateResult>()?,
        schema_pair::<TerminalSessionId>()?,
        schema_pair::<TerminalSessionStatus>()?,
        schema_pair::<TerminalSessionSummary>()?,
        schema_pair::<TerminalSpawnParams>()?,
        schema_pair::<TerminalSpawnResult>()?,
        schema_pair::<TerminalListParams>()?,
        schema_pair::<TerminalListResult>()?,
        schema_pair::<TerminalAttachParams>()?,
        schema_pair::<TerminalAttachResult>()?,
        schema_pair::<TerminalInputParams>()?,
        schema_pair::<TerminalInputResult>()?,
        schema_pair::<TerminalResizeParams>()?,
        schema_pair::<TerminalResizeResult>()?,
        schema_pair::<TerminalDetachParams>()?,
        schema_pair::<TerminalDetachResult>()?,
        schema_pair::<TerminalCloseParams>()?,
        schema_pair::<TerminalCloseResult>()?,
        schema_pair::<TerminalStreamEvent>()?,
        schema_pair::<TerminalEventParams>()?,
        schema_pair::<TrustState>()?,
        schema_pair::<ExecutionContext>()?,
        schema_pair::<WorkspaceScope>()?,
        schema_pair::<SandboxProfile>()?,
        schema_pair::<ProcessExecPolicy>()?,
        schema_pair::<PermissionPolicy>()?,
        schema_pair::<NetworkPolicy>()?,
        schema_pair::<EnvPolicy>()?,
        schema_pair::<WorkspaceCapabilityUnsupported>()?,
        schema_pair::<SessionOverviewQuery>()?,
        schema_pair::<SessionOverviewResult>()?,
        schema_pair::<SessionOverviewLaneStatus>()?,
        schema_pair::<ApprovalAttentionState>()?,
        schema_pair::<SpaceId>()?,
        schema_pair::<ProjectId>()?,
        schema_pair::<NavigationSpace>()?,
        schema_pair::<NavigationProject>()?,
        schema_pair::<ConversationPlacement>()?,
        schema_pair::<NavigationConversation>()?,
        schema_pair::<NavigationAgentRow>()?,
        schema_pair::<NavigationSnapshot>()?,
        schema_pair::<DaemonNavigationSnapshotParams>()?,
        schema_pair::<DaemonNavigationSnapshotResult>()?,
        schema_pair::<DaemonNavigationIntent>()?,
        schema_pair::<DaemonNavigationIntentParams>()?,
        schema_pair::<DaemonNavigationIntentResult>()?,
        schema_pair::<DaemonNavigationSubscribeParams>()?,
        schema_pair::<DaemonNavigationSubscribeResult>()?,
        schema_pair::<DaemonNavigationInvalidatedParams>()?,
        schema_pair::<DesktopDaemonLifecycleStatus>()?,
        schema_pair::<DesktopDaemonLifecycleProjection>()?,
        schema_pair::<DaemonInitializeParams>()?,
        schema_pair::<DaemonInitializeResult>()?,
        schema_pair::<DaemonRuntimeMode>()?,
        schema_pair::<WorkspaceSelector>()?,
        schema_pair::<DaemonSessionOpenParams>()?,
        schema_pair::<DaemonSessionOpenResult>()?,
        schema_pair::<DaemonSessionAttachParams>()?,
        schema_pair::<DaemonSessionAttachResult>()?,
        schema_pair::<DaemonApprovalDecideParams>()?,
        schema_pair::<DaemonApprovalDecideResult>()?,
        schema_pair::<DaemonServerCapabilities>()?,
        schema_pair::<DaemonControlStatusResult>()?,
        schema_pair::<DaemonStatusParams>()?,
        schema_pair::<DaemonStatusResult>()?,
        schema_pair::<DaemonDiagnosticsParams>()?,
        schema_pair::<DaemonDiagnostics>()?,
        schema_pair::<DaemonDiagnosticError>()?,
        schema_pair::<DaemonDiagnosticTokenUsage>()?,
        schema_pair::<DaemonSandboxCapabilitySnapshot>()?,
        schema_pair::<DaemonProviderHealthDiagnostic>()?,
        schema_pair::<DaemonSubscribeParams>()?,
        schema_pair::<DaemonSubscribeResult>()?,
        schema_pair::<DelegateRequest>()?,
        schema_pair::<ListApprovalsQuery>()?,
        schema_pair::<ApprovalSnapshotResult>()?,
        schema_pair::<crate::wire::WorkItemKey>()?,
        schema_pair::<crate::wire::WorkItem>()?,
        schema_pair::<WorkItemListResult>()?,
        schema_pair::<WorkItemRefreshParams>()?,
        schema_pair::<WorkItemDismissParams>()?,
        schema_pair::<WorkItemDismissResult>()?,
        schema_pair::<WorkItemTriggerParams>()?,
        schema_pair::<WorkItemTriggerResult>()?,
        schema_pair::<GetArtifactQuery>()?,
        schema_pair::<GetRunQuery>()?,
        schema_pair::<GetSessionQuery>()?,
        schema_pair::<ListArtifactsQuery>()?,
        schema_pair::<ArtifactSnapshotResult>()?,
        schema_pair::<ListReceiptsRequest>()?,
        schema_pair::<ListReceiptsResult>()?,
        schema_pair::<PromoteReceiptRequest>()?,
        schema_pair::<QuarantineReceiptRequest>()?,
        schema_pair::<OutputContractKind>()?,
        schema_pair::<CapsuleResult>()?,
        schema_pair::<DebugResult>()?,
        schema_pair::<PatchResult>()?,
        schema_pair::<ReviewResult>()?,
        schema_pair::<ReviewVerdict>()?,
        schema_pair::<ReviewFinding>()?,
        schema_pair::<FindingSeverity>()?,
        schema_pair::<TestResult>()?,
        schema_pair::<PlanResult>()?,
        schema_pair::<PlanStep>()?,
        schema_pair::<ValidationError>()?,
        schema_pair::<VoicePermissionState>()?,
        schema_pair::<VoicePhase>()?,
        schema_pair::<VoiceEvent>()?,
        schema_pair::<CapsuleRecipe>()?,
        schema_pair::<ListRecipesParams>()?,
        schema_pair::<RecipeListResponse>()?,
        schema_pair::<RecipeValidationError>()?,
        schema_pair::<RecipeResolutionError>()?,
        schema_pair::<ListRunsQuery>()?,
        schema_pair::<RunListFilter>()?,
        schema_pair::<ListNativeRunsRequest>()?,
        schema_pair::<RunListEntry>()?,
        schema_pair::<ListNativeRunsResult>()?,
        schema_pair::<RunLineageGraphRequest>()?,
        schema_pair::<RunLineageGraphEdge>()?,
        schema_pair::<RunLineageGraphResult>()?,
        schema_pair::<GetRunTimelineQuery>()?,
        schema_pair::<RunTimeline>()?,
        schema_pair::<RunTimelineRun>()?,
        schema_pair::<RunTimelineEventKind>()?,
        schema_pair::<RunTimelineEvent>()?,
        schema_pair::<RunTimelineEventPayload>()?,
        schema_pair::<ListSessionsQuery>()?,
        ("ProtocolVersion", protocol_version_schema_value()),
        schema_pair::<RunId>()?,
        schema_pair::<RunHarnessKind>()?,
        schema_pair::<RunDetail>()?,
        schema_pair::<RunRecord>()?,
        schema_pair::<RunStatus>()?,
        schema_pair::<RunSummary>()?,
        schema_pair::<ResumeRunRequest>()?,
        schema_pair::<ResumeRunResult>()?,
        schema_pair::<ResumeRunState>()?,
        schema_pair::<ForkRunRequest>()?,
        schema_pair::<ForkRunResult>()?,
        schema_pair::<ContinueRunRequest>()?,
        schema_pair::<ContinueRunResult>()?,
        schema_pair::<SwitchAccountAndResumeRequest>()?,
        schema_pair::<SwitchAccountAndResumeResult>()?,
        schema_pair::<SpawnRunRequest>()?,
        schema_pair::<SpawnRunResult>()?,
        schema_pair::<JoinRunRequest>()?,
        schema_pair::<JoinRunResult>()?,
        schema_pair::<SubscribeRunEventsRequest>()?,
        schema_pair::<RunEventDelta>()?,
        schema_pair::<RunEventStreamError>()?,
        schema_pair::<RunEventStreamPayload>()?,
        schema_pair::<RunEventStreamItem>()?,
        schema_pair::<SubscribeRunEventsResult>()?,
        schema_pair::<SessionAuthority>()?,
        schema_pair::<SessionId>()?,
        schema_pair::<SessionOverview>()?,
        schema_pair::<SessionStatus>()?,
        schema_pair::<SessionSummary>()?,
        schema_pair::<StartRunCommand>()?,
        schema_pair::<DaemonRunCompleteWithResultParams>()?,
        schema_pair::<WorkflowDefinition>()?,
        schema_pair::<WorkflowSourceBinding>()?,
        schema_pair::<WorkflowSourceKind>()?,
        schema_pair::<WorkflowOrchestratorPolicy>()?,
        schema_pair::<WorkflowRetryPolicy>()?,
        schema_pair::<WorkflowPolicy>()?,
        schema_pair::<WorkflowApprovalPolicy>()?,
        schema_pair::<WorkflowFileWriteApproval>()?,
        schema_pair::<WorkflowProcessApproval>()?,
        schema_pair::<WorkflowNetworkApproval>()?,
        schema_pair::<WorkflowRuntimeProfileRef>()?,
        schema_pair::<WorkflowOutputsPolicy>()?,
        schema_pair::<WorkflowOutputRequirement>()?,
        schema_pair::<WorkflowBudgets>()?,
        schema_pair::<WorkflowBudgetLimits>()?,
        schema_pair::<WorkflowLoadParams>()?,
        schema_pair::<WorkflowReloadParams>()?,
        schema_pair::<WorkflowValidateParams>()?,
        schema_pair::<WorkflowValidationReport>()?,
        schema_pair::<WorkflowValidationError>()?,
        schema_pair::<WorkflowStatusResult>()?,
        schema_pair::<WorkflowLoadedStatus>()?,
        schema_pair::<WorkflowReloadOutcome>()?,
    ];
    schemas.extend(selected_runtime_schemas(CANCELLATION_SCHEMAS)?);
    Ok(schemas)
}

fn agent_runtime_runtime_schemas()
-> Result<Vec<(&'static str, serde_json::Value)>, ProtocolExportError> {
    Ok(vec![
        schema_pair::<AgentRuntimeStrategyId>()?,
        schema_pair::<AgentRuntimeModelId>()?,
        schema_pair::<AgentRuntimeModelRef>()?,
        schema_pair::<AgentRuntimeMediaCapability>()?,
        schema_pair::<AgentRuntimeMediaCapabilities>()?,
        schema_pair::<AgentRuntimeStrategyHealthStatus>()?,
        schema_pair::<AgentRuntimeStrategyHealth>()?,
        schema_pair::<AgentRuntimeStrategyInfo>()?,
        schema_pair::<AuthMethodId>()?,
        schema_pair::<AuthMethodRef>()?,
        schema_pair::<AuthProfileId>()?,
        schema_pair::<AuthProfileConnectionState>()?,
        schema_pair::<AuthProfileLoginMethod>()?,
        schema_pair::<AuthProfileRef>()?,
        schema_pair::<AuthProfilePreferences>()?,
        schema_pair::<AuthProfileUsage>()?,
        schema_pair::<AuthProfileUsageWindow>()?,
        schema_pair::<AuthProfileState>()?,
        schema_pair::<AuthProfileLoginChallenge>()?,
        schema_pair::<AuthProfileLoginResult>()?,
        schema_pair::<AuthProfileLogoutResult>()?,
        schema_pair::<RuntimeExtensionId>()?,
        schema_pair::<RuntimeExtensionDescriptor>()?,
        schema_pair::<RuntimeExtensionAvailability>()?,
        schema_pair::<RuntimeExtensionMcpServer>()?,
        schema_pair::<RuntimeExtensionMcpStdioServer>()?,
        schema_pair::<RuntimeExtensionMcpHttpServer>()?,
        schema_pair::<RuntimeExtensionEnvVar>()?,
        schema_pair::<RuntimeExtensionHttpHeader>()?,
        schema_pair::<RuntimeExtensionState>()?,
        schema_pair::<RuntimeProfileId>()?,
        schema_pair::<RuntimePolicyMode>()?,
        schema_pair::<RuntimeProfileExecutionKind>()?,
        schema_pair::<RuntimeProfileSummary>()?,
        schema_pair::<RuntimeProfilePatch>()?,
        schema_pair::<AgentRuntimeSelection>()?,
        schema_pair::<AgentRuntimeSnapshot>()?,
        schema_pair::<GetAgentRuntimeQuery>()?,
        schema_pair::<DaemonAgentRuntimePatchProfileParams>()?,
        schema_pair::<DaemonAgentRuntimeAuthLoginParams>()?,
        schema_pair::<DaemonAgentRuntimeAuthLoginCompleteParams>()?,
        schema_pair::<DaemonAgentRuntimeAuthLogoutParams>()?,
        schema_pair::<DaemonAgentRuntimeSetExtensionEnabledParams>()?,
    ])
}

fn schema_pair<T: JsonSchema>() -> Result<(&'static str, serde_json::Value), ProtocolExportError> {
    Ok((simple_type_name::<T>(), schema_value::<T>()?))
}

fn write_protocol_version_schema(schema_dir: &Path) -> Result<(), ProtocolExportError> {
    let schema = protocol_version_schema_value();
    let schema_json = serde_json::to_string_pretty(&schema)?;
    fs::write(
        schema_dir.join("ProtocolVersion.json"),
        format!("{schema_json}\n"),
    )?;
    Ok(())
}

fn schema_value<T: JsonSchema>() -> Result<serde_json::Value, ProtocolExportError> {
    Ok(serde_json::to_value(schema_for!(T))?)
}

fn protocol_version_schema_value() -> serde_json::Value {
    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "ProtocolVersion",
        "type": "string",
        "const": PROTOCOL_VERSION,
    })
}

fn simple_type_name<T>() -> &'static str {
    std::any::type_name::<T>()
        .rsplit("::")
        .next()
        .expect("type name should be present")
}
