[package]
name = "ta-jsonrpc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
futures-util.workspace = true
interprocess.workspace = true
serde.workspace = true
serde_json.workspace = true
ta-host-platform = { path = "../ta-host-platform" }
ta-observability = { path = "../ta-observability" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true

[lints]
workspace = true
