packages:
  - packages/*

overrides:
  "@gpuix/native": 0.4.0
  "@gpuix/react": 0.4.0

minimumReleaseAge: 10080
trustPolicy: no-downgrade

minimumReleaseAgeExclude:
  - "@gpuix/native"
  - "@gpuix/native-*"
  - "@gpuix/react"
  - "eventsource-parser"
