/**
 * Rust-owned daemon boundary. Credentials, authorities, socket paths, and
 * cursors never cross this API; method results are public protocol JSON.
 */
export declare class NativeDaemonBridge {
  constructor();
  start(): Promise<string>;
  readDesktopSettings(): Promise<string | null>;
  writeDesktopSettings(documentJson: string): Promise<void>;
  listSessions(): Promise<string>;
  openSession(paramsJson: string): Promise<string>;
  attachSession(sessionId: string): Promise<string>;
  setSessionNextRunSelection(paramsJson: string): Promise<string>;
  navigationSnapshot(search?: string | null): Promise<string>;
  navigationIntent(intentJson: string): Promise<string>;
  openProject(path: string, trustAcknowledged: boolean): Promise<string>;
  workspaceFileTree(paramsJson: string): Promise<string>;
  readWorkspaceFile(paramsJson: string): Promise<string>;
  materializeWorkspaceImage(paramsJson: string): Promise<string>;
  writeWorkspaceFile(paramsJson: string): Promise<string>;
  openWorkspaceFileExternal(paramsJson: string): Promise<string>;
  codeHostAccounts(): Promise<string>;
  connectCodeHostAccount(paramsJson: string): Promise<string>;
  disconnectCodeHostAccount(paramsJson: string): Promise<string>;
  codeHostRepositoryContext(paramsJson: string): Promise<string>;
  prepareCodeHostPush(paramsJson: string): Promise<string>;
  applyCodeHostPush(paramsJson: string): Promise<string>;
  codeHostPullRequests(paramsJson: string): Promise<string>;
  codeHostPullRequestDetail(paramsJson: string): Promise<string>;
  ensureCodeHostPullRequest(paramsJson: string): Promise<string>;
  codeHostPullRequestChecks(paramsJson: string): Promise<string>;
  codeHostPullRequestActivity(paramsJson: string): Promise<string>;
  createCodeHostPullRequestComment(paramsJson: string): Promise<string>;
  gitSnapshot(paramsJson: string): Promise<string>;
  gitDiff(paramsJson: string): Promise<string>;
  gitStage(paramsJson: string): Promise<string>;
  gitUnstage(paramsJson: string): Promise<string>;
  gitCommit(paramsJson: string): Promise<string>;
  gitCheckpointList(paramsJson: string): Promise<string>;
  gitCheckpointPrepareRevert(paramsJson: string): Promise<string>;
  gitCheckpointApplyRevert(paramsJson: string): Promise<string>;
  getAgentRuntime(): Promise<string>;
  diagnosticsSnapshot(): Promise<string>;
  loginAuthProfile(paramsJson: string): Promise<string>;
  completeAuthProfileLogin(paramsJson: string): Promise<string>;
  logoutAuthProfile(paramsJson: string): Promise<string>;
  setAuthProfilePreferences(paramsJson: string): Promise<string>;
  listApprovals(queryJson: string): Promise<string>;
  threadWorkspace(): Promise<string>;
  updateThreadWorkspace(commandJson: string): Promise<string>;
  agentTurnsPage(sessionId: string, queryJson: string): Promise<string>;
  listArtifacts(sessionId: string, queryJson: string): Promise<string>;
  getArtifact(sessionId: string, queryJson: string): Promise<string>;
  materializeArtifactImage(sessionId: string, queryJson: string): Promise<string>;
  decideApproval(paramsJson: string): Promise<string>;
  listRecipes(): Promise<string>;
  listWorkItems(queryJson: string): Promise<string>;
  refreshWorkItems(paramsJson: string): Promise<string>;
  dismissWorkItem(paramsJson: string): Promise<string>;
  triggerWorkItem(sessionId: string, paramsJson: string): Promise<string>;
  createScheduledWork(paramsJson: string): Promise<string>;
  listScheduledWork(): Promise<string>;
  cancelScheduledWork(paramsJson: string): Promise<string>;
  inspectPluginPackage(paramsJson: string): Promise<string>;
  installPluginPackage(paramsJson: string): Promise<string>;
  listPluginInstallations(): Promise<string>;
  uninstallPlugin(paramsJson: string): Promise<string>;
  spawnTerminal(paramsJson: string): Promise<string>;
  listTerminals(paramsJson: string): Promise<string>;
  terminalInput(paramsJson: string): Promise<string>;
  resizeTerminal(paramsJson: string): Promise<string>;
  closeTerminal(paramsJson: string): Promise<string>;
  subscribeTerminalEvents(terminalId: string, callback: (eventJson: string) => void): Promise<string>;
  releaseTerminalEventSubscription(): string;
  startRun(commandJson: string): Promise<string>;
  voicePermissionState(): string;
  requestVoicePermission(callback: (permissionJson: string) => void): string;
  subscribeVoiceState(callback: (eventJson: string) => void): string;
  forkRun(requestJson: string): Promise<string>;
  continueRun(requestJson: string): Promise<string>;
  switchAccountAndResume(requestJson: string): Promise<string>;
  spawnRun(requestJson: string): Promise<string>;
  joinRun(requestJson: string): Promise<string>;
  listNativeRuns(sessionId: string, requestJson: string): Promise<string>;
  runLineageGraph(sessionId: string, requestJson: string): Promise<string>;
  getRun(sessionId: string, queryJson: string): Promise<string>;
  runTimeline(sessionId: string, queryJson: string): Promise<string>;
  activityPage(sessionId: string, queryJson: string): Promise<string>;
  replayRunEvents(sessionId: string, queryJson: string): Promise<string>;
  cancelRun(runId: string): Promise<string>;
  releaseRunEventSubscription(): string;
  subscribeRunEvents(sessionId: string, runId: string, callback: (eventJson: string) => void): Promise<string>;
  subscribeLifecycle(callback: (projectionJson: string) => void): Promise<string>;
  close(): Promise<string>;
}
