[package]
name = "ta-exec"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nix.workspace = true
portable-pty.workspace = true
ta-sandbox = { path = "../ta-sandbox" }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
